"""empty message

Revision ID: 2810dfb893b0
Revises: f93c0adfe51a
Create Date: 2020-08-23 17:37:35.365709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2810dfb893b0'
down_revision = 'f93c0adfe51a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('FacultyAndStaff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_credentials', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('FacultyAndStaff', schema=None) as batch_op:
        batch_op.drop_column('google_credentials')

    # ### end Alembic commands ###
