"""empty message

Revision ID: 6fa9a49ab57a
Revises: f93c0adfe51a
Create Date: 2020-08-27 11:19:41.442901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6fa9a49ab57a"
down_revision = "f93c0adfe51a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ClassSchedule", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("interventionLog_id", sa.Integer(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("learningLab", sa.Boolean(), nullable=False, server_default="0")
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_ClassSchedule_interventionLog_id_InterventionLog"),
            "InterventionLog",
            ["interventionLog_id"],
            ["id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("FacultyAndStaff", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("google_picture", sa.String(length=256), nullable=True)
        )
        batch_op.add_column(
            sa.Column("google_sub", sa.String(length=256), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("FacultyAndStaff", schema=None) as batch_op:
        batch_op.drop_column("google_sub")
        batch_op.drop_column("google_picture")

    with op.batch_alter_table("ClassSchedule", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_ClassSchedule_interventionLog_id_InterventionLog"),
            type_="foreignkey",
        )
        batch_op.drop_column("learningLab")
        batch_op.drop_column("interventionLog_id")

    # ### end Alembic commands ###
