"""empty message

Revision ID: 9ae440a491cd
Revises: ac9eb7acb927
Create Date: 2020-08-10 21:19:31.831687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ae440a491cd'
down_revision = 'ac9eb7acb927'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('SchoolCalendar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('startTmiPeriod', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('tmiDay', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('SchoolCalendar', schema=None) as batch_op:
        batch_op.drop_column('tmiDay')
        batch_op.drop_column('startTmiPeriod')

    # ### end Alembic commands ###
