"""empty message

Revision ID: 9b5bc20d0835
Revises: 
Create Date: 2020-08-04 18:53:21.268482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b5bc20d0835'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FacultyAndStaff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(length=50), nullable=False),
    sa.Column('lastName', sa.String(length=50), nullable=False),
    sa.Column('position', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phoneNumber', sa.String(length=20), nullable=True),
    sa.Column('chattStateANumber', sa.String(length=20), nullable=True),
    sa.Column('myersBrigg', sa.Integer(), nullable=True),
    sa.Column('house', sa.String(length=20), nullable=True),
    sa.Column('houseGrade', sa.Integer(), nullable=True),
    sa.Column('twitterAccount', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chattStateANumber')
    )
    op.create_table('InterventionType',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interventionType', sa.String(length=30), nullable=False),
    sa.Column('maxLevel', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('SchoolCalendar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('classDate', sa.Date(), nullable=False),
    sa.Column('day', sa.String(length=1), nullable=False),
    sa.Column('dayNumber', sa.Integer(), nullable=False),
    sa.Column('stemSchoolDay', sa.Boolean(), nullable=True),
    sa.Column('phaseIISchoolDay', sa.Boolean(), nullable=True),
    sa.Column('chattStateSchoolDay', sa.Boolean(), nullable=True),
    sa.Column('seniorErDay', sa.Boolean(), nullable=True),
    sa.Column('seniorUpDay', sa.Boolean(), nullable=True),
    sa.Column('juniorErDay', sa.Boolean(), nullable=True),
    sa.Column('juniorUpDay', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chattStateANumber', sa.String(length=20), nullable=False),
    sa.Column('firstName', sa.String(length=50), nullable=False),
    sa.Column('lastName', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('yearOfGraduation', sa.Integer(), nullable=False),
    sa.Column('house', sa.String(length=20), nullable=False),
    sa.Column('googleCalendarId', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chattStateANumber')
    )
    op.create_table('ClassSchedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schoolYear', sa.Integer(), nullable=False),
    sa.Column('semester', sa.String(length=20), nullable=False),
    sa.Column('chattStateANumber', sa.String(length=20), nullable=False),
    sa.Column('campus', sa.String(length=50), nullable=False),
    sa.Column('className', sa.String(length=50), nullable=False),
    sa.Column('teacherLastName', sa.String(length=50), nullable=False),
    sa.Column('staffID', sa.Integer(), nullable=True),
    sa.Column('online', sa.Boolean(), nullable=False),
    sa.Column('indStudy', sa.Boolean(), nullable=False),
    sa.Column('classDays', sa.String(length=10), nullable=False),
    sa.Column('startTime', sa.Time(), nullable=True),
    sa.Column('endTime', sa.Time(), nullable=True),
    sa.Column('comment', sa.String(length=250), nullable=True),
    sa.Column('googleCalendarEventID', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['chattStateANumber'], ['Student.chattStateANumber'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staffID'], ['FacultyAndStaff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('DailyAttendanceLog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('absenceDate', sa.Date(), nullable=False),
    sa.Column('createDate', sa.Date(), nullable=False),
    sa.Column('attendanceCode', sa.String(length=1), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('staffID', sa.Integer(), nullable=False),
    sa.Column('assignTmi', sa.Boolean(), nullable=False),
    sa.Column('recordDeleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['staffID'], ['FacultyAndStaff.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['Student.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('InterventionLog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('intervention_id', sa.Integer(), nullable=False),
    sa.Column('interventionLevel', sa.Integer(), nullable=False),
    sa.Column('createDate', sa.Date(), nullable=False),
    sa.Column('startDate', sa.Date(), nullable=False),
    sa.Column('endDate', sa.Date(), nullable=False),
    sa.Column('staffID', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('tmiMinutes', sa.Integer(), nullable=True),
    sa.Column('tmiMinutesServed', sa.Integer(), nullable=True),
    sa.Column('tmiMinutesRemaining', sa.Integer(), nullable=True),
    sa.Column('inTmiNow', sa.Boolean(), nullable=True),
    sa.Column('erSession', sa.String(length=50), nullable=True),
    sa.Column('interventionStatus', sa.String(length=50), nullable=True),
    sa.Column('recordDeleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['intervention_id'], ['InterventionType.id'], ),
    sa.ForeignKeyConstraint(['staffID'], ['FacultyAndStaff.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['Student.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ClassAttendanceLog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('classSchedule_id', sa.Integer(), nullable=False),
    sa.Column('classDate', sa.Date(), nullable=False),
    sa.Column('attendanceCode', sa.String(length=2), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('assignTmi', sa.Boolean(), nullable=False),
    sa.Column('interventionLog_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['classSchedule_id'], ['ClassSchedule.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['interventionLog_id'], ['InterventionLog.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ClassAttendanceLog')
    op.drop_table('InterventionLog')
    op.drop_table('DailyAttendanceLog')
    op.drop_table('ClassSchedule')
    op.drop_table('Student')
    op.drop_table('SchoolCalendar')
    op.drop_table('InterventionType')
    op.drop_table('FacultyAndStaff')
    # ### end Alembic commands ###
