"""empty message

Revision ID: ac9eb7acb927
Revises: 5ef8361d836d
Create Date: 2020-08-09 13:19:49.838963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac9eb7acb927'
down_revision = '5ef8361d836d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Parents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Parents', schema=None) as batch_op:
        batch_op.drop_column('comment')

    # ### end Alembic commands ###
