"""empty message

Revision ID: f93c0adfe51a
Revises: ed306c6b2697
Create Date: 2020-08-21 08:36:31.567889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f93c0adfe51a'
down_revision = 'ed306c6b2697'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('FacultyAndStaff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_picture', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('google_sub', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('FacultyAndStaff', schema=None) as batch_op:
        batch_op.drop_column('google_sub')
        batch_op.drop_column('google_picture')

    # ### end Alembic commands ###
